### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by Victorgonbu**
## Add tests for: 
- Todo class logic
- Project class logic

The TodoUI and ProjectUI are the modules in charge to manipulate all the doom elements and I think the only way of testing these is using integration tests.

Thank you very much for reviewing.

### CODE REVIEW

**Review by wathigo — CHANGES_REQUESTED** [review]
## Changes Required :o: 
Great job on this project.
Let's add more tests before we move on.

### REQUIRED
Let's add tests for the storage factory function. We don't need to test functions that interact with DOM for now.

**After making the changes, submit another request for review.**

**Happy Coding :computer: 
Simon Wathigo**

**Review by trekab — CHANGES_REQUESTED** [review]
### Changes Required! :recycle: 
Well done so far, @Shaqri! :+1: However, for this project, you're expected to test all your functions. e.g. You tested only 3/7 methods from your project module. Please add more tests to improve your test coverage.

__N.B:__ Don't worry about integration tests.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Comment by Victorgonbu** [comment]
Hey @trekab! Thank you very much for reviewing.
It's expected but not necessary, all of the methods that I did not test are either being used by other methods I tested or using a third-party method. Anyways I added tests for the methods being used by other methods but no for the ones that are just using a third party method since there may be already tests for those, right?

**Comment by trekab** [comment]
> Hey @trekab! Thank you very much for reviewing.
> It's expected but not necessary, all of the methods that I did not test are either being used by other methods I tested or using a third-party method. Anyways I added tests for the methods being used by other methods but no for the ones that are just using a third party method since there may be already tests for those, right?

Sounds and looks good to me. You're right, it is redundant to test methods/functions that are being used by other methods whose tests you've already written. Well done for putting in the extra effort to write them anyway! :+1:

**Review by Torres-ssf — APPROVED** [review]
### PR Approved :tada: 
Hi @Shaqri :hand: 
Great job on this project
Good luck with the next one.

Happy coding :computer: 
**Sergio Torres**

**Pull request merged**
